apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.nameOverride}}"
spec:
  selector:
    matchLabels:
      app: event-hub-dao
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: event-hub-dao
        tier: backend
        track: stable
    spec:
      volumes:
      - name: event-hub-dao-secrets-volume
        secret:
          secretName: event-hub-dao-secret
      containers:
        - name: event-hub-dao
          image: "gcr.io/{{ .Values.gcp_project }}/{{.Values.nameOverride}}:{{.Values.image.tag}}"
          imagePullPolicy: "Always"
          volumeMounts:
          - name: event-hub-dao-secrets-volume
            mountPath: /var/secrets/event-hub-dao-secret
          env:
          - name: GOOGLE_CLOUD_PROJECT
            value: "{{ .Values.gcp_project }}"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/event-hub-dao-secret/{{ .Values.gcp_project }}-dao-sa.json
          ports:
            - name: http
              containerPort: 8080